resolver: lts-14.27

packages:
- .

extra-deps:
- github: tmcdonell/accelerate
  commit: da18b951f85c969971929199e0b03114ff210b6c

- github: tmcdonell/accelerate-llvm
  commit: 69a16bafdce0ab2b2ab4428e1f4a94e642eb3a68
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx

- github: tmcdonell/lens-accelerate
  commit: b74eb8098735b1ad6cff3c5655af03d3f29b9f8e

flags:
  accelerate:
    debug: true

